config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'posts#index'
  resources :posts 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  body       :text
#  author     :string
#

class Post < ApplicationRecord
  validate :has_sunny_in_body
  validates :body, presence: true, length: { minimum: 7 }
  validates :author, presence: true 

  def has_sunny_in_body
    unless self.body && self.body.include?("Sunny")
      errors[:body] << "Doesn't have a reference to Sunny!"
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def new
    @post = Post.new 
    render :new
  end

  def create
    @post = Post.new(post_params)
    if @post.valid?
      @post.save
      redirect_to root_url
    else
      flash[:errors] = @post.errors.full_messages
      render :new
    end
  end

  def destroy
    @post = Post.find_by(id: params[:id])
    if @post
      @post.destroy
    else
      flash[:errors] = ["Post doesn't exist"]
    end
    redirect_to root_url
  end

  private

  def post_params
    params.require(:post).permit(:body, :author)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/application/_new_post_form.html.erb
<!-- <form class="" action='<%= posts_url %>' method="post">
   <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <textarea name="post[body]"></textarea>
  <label for="post_author"></label>
  <select name="post[author]">
      <option disabled selected>-- Please select an author --</option>
      <option value="sunny">Sunny</option>
      <option value="not sunny">Not Sunny</option>
  </select>
  <br>

  <input type="submit" value="Create post" />
</form>


<p> This is just practicing building a radio form for selecting author: </p>
<form class="" action='<%= posts_url %>' method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="radio" name='post[author]' value="sunny"> Sunny <br />
  <input type="radio" name='post[author]' value="not-sunny"> Not Sunny <br />
  <input type="submit" value="Submit Author via Radio Btn">
</form>


<p> This is just practicing building a checkbox form for selecting author: </p>
<form class="" action='<%= posts_url %>' method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="checkbox" name="post[author][]" value="sunny"> Sunny <br />
  <input type="checkbox" name="post[author][]" value="not-sunny"> Not Sunny <br />
  <input type="submit" value="Submit all authors of this post">
</form> -->

<h1>The form </h1>
<%= form_for(@post) do |f| %> <!-- build out normal form input -->
  <%= f.label :body %>
  <%= f.text_area :body%>
  <%= f.select :author, [['--please select author--', '0'], ['Sunny', 'sunny'], ['Not Sunny', 'not sunny']], {disabled: '0', selected: '0'} %>
  <%= f.submit 'Create Post' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GoalTracker</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <% if flash[:errors] %>
      <% flash[:errors].each do |error| %>
        <%= error %>
        <br />
      <% end %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<h1>All Posts</h1>
<ul>
  <% @posts.each do |post| %>
    <li>
      <%= post.body %>
      <!-- build partial for post -->
    </li>
  <% end %>
</ul>

<%= link_to "Create a new post", new_post_url %>

app/views/posts/new.html.erb
<%= render 'new_post_form' %>